kind: pipeline
name: default

steps:
  - name: build
    image: python:3.6-alpine
    commands:
      - apt-get install -y git-core
      - pip install --upgrade pip setuptools wheel
      - pip install mkdocs
      - mkdocs gh-deploy
