site_name: Lobaro Documentation
site_description: Online documentation of the Lobaro GmbH, Industrial IoT Solutions. Manuals for our IoT Devices.
theme:
  #    name: cinder
  name: material
  favicon: favicon.ico
  logo: img/lobaro-rings-circle.svg
  #    name: readthedocs
  highlightjs: true
  palette:
    primary: 'white'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Cousine'

  feature:
    tabs: false

repo_url: "https://github.com/lobaro/docs"
copyright: 'Lobaro GmbH'
use_directory_urls: false
markdown_extensions:
  - attr_list
  - def_list
  - toc:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - "css/lobarodoc.css"
extra_javascript:
  - "js/mermaid.min.js"
nav:
  - Home: index.md
  - LoRaWAN Sensors:
      - wMBUS Bridge:
          - Manual: lorawan-sensors/wmbus-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/wmbus-lorawan/firmware.md
      - Modbus Bridge:
          - Manual: lorawan-sensors/modbus-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/modbus-lorawan/firmware.md
      - EDL21 Bridge:
          - Manual: lorawan-sensors/edl21-opto-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/edl21-opto-lorawan/firmware.md
      - 1-Wire Bridge:
          - Manual: lorawan-sensors/1-wire-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/1-wire-lorawan/firmware.md
      - GPS Tracker:
          - Manual: lorawan-sensors/gps-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/gps-lorawan/firmware.md
      - Usonic Distance Sensor:
          - Manual: lorawan-sensors/usonic-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/usonic-lorawan/firmware.md
      - Temp. + rH. Sensor:
          - Manual: lorawan-sensors/humidity-temp-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/humidity-temp-lorawan/firmware.md
      - Liquid Level Sensor:
          - Manual: lorawan-sensors/pressure-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/pressure-lorawan/firmware.md
  - Lobaro Dashboard: dashboard/index.md
  - Lobaro Tools:
      - Lobaro Maintenance Tool: tools/lobaro-tool.md
      - USB Config Adapter: tools/usb-config-adapter.md
  - Knowledge base:
      - CRON Expressions: background/cron-expressions.md
      - LoRaWAN: background/lorawan.md
      - OBIS Codes: background/obis-codes.md
      - WEEE Disposal: background/weee-disposal.md
  #    - Company Home: https://www.lobaro.com/lobaro-iot-produkte-dienste/

  - Contact / Impressum: https://www.lobaro.com/contact/
