site_name: Lobaro Documentation

theme:
    name: cinder
#    name: readthedocs
    highlightjs: true
repo_url: "https://github.com/lobaro/docs"
site_favicon: favicon.ico
markdown_extensions:
    - admonition
