site_name: Lobaro Documentation
site_description: Online documentation of the Lobaro GmbH, Industrial IoT Solutions. Manuals for our IoT Devices.
theme:
  #    name: cinder
  name: material
  favicon: favicon.ico
  logo: img/lobaro-rings-circle.svg
  #    name: readthedocs
  highlightjs: true
  palette:
    primary: 'white'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Cousine'

  feature:
    tabs: false

google_analytics:
  - 'UA-69919312-3'
  - 'auto'

repo_url: "https://github.com/lobaro/docs"
copyright: 'Lobaro GmbH'
use_directory_urls: false
markdown_extensions:
  - attr_list # enables CSS e.g. {: target="_blank"}
  - def_list
  - markdown_include.include: # enables including other files into pages with {!filename!}
      base_path: docs
  - toc:
  - admonition # Enables alert boxes with e.g. !!! note "title"
  - footnotes
  - codehilite
# see https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
#  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - "css/lobarodoc.css"
  - "css/simple-lightbox.min.css"
extra_javascript:
  - "js/mermaid.min.js"
  - 'js/simple-lightbox.js'
nav:
  - Documentation Start: index.md
  - LoRaWAN Sensors:
      - wMBUS Bridge:
          - Manual: lorawan-sensors/wmbus-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/wmbus-lorawan/firmware.md
      - Modbus Bridge:
          - Manual: lorawan-sensors/modbus-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/modbus-lorawan/firmware.md
          - Versions: lorawan-sensors/modbus-lorawan/versions.md
      - EDL21 Bridge:
          - Manual: lorawan-sensors/edl21-opto-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/edl21-opto-lorawan/firmware.md
      - 1-Wire Bridge:
          - Manual: lorawan-sensors/1-wire-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/1-wire-lorawan/firmware.md
      - GPS Tracker:
          - Manual: lorawan-sensors/gps-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/gps-lorawan/firmware.md
      - Usonic Distance Sensor:
          - Manual: lorawan-sensors/usonic-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/usonic-lorawan/firmware.md
      - Temp. + rH. Sensor:
          - Manual: lorawan-sensors/humidity-temp-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/humidity-temp-lorawan/firmware.md
      - Pressure Sensor:
          - Manual: lorawan-sensors/pressure-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/pressure-lorawan/firmware.md
      - Environment Sensor:
          - Manual: lorawan-sensors/environment-lorawan/index.md
          - Firmware & Changelog: lorawan-sensors/environment-lorawan/firmware.md
      - LoRaWAN Modbus Gateway:
          - Manual: lorawan-sensors/lorawan-modbus-gateway/index.md
  - NB-IoT / LTE-M Sensors:
      - wMBus Gateway: nbiot-sensors/wmbus-nbiot/index.md
  - Background Articles:
      - Hardware Variations: hardware.md
      - CRON Expressions: background/cron-expressions.md
      - LoRaWAN: background/lorawan.md
      - OBIS Codes: background/obis-codes.md
      - WEEE Disposal: background/weee-disposal.md
  #    - Company Home: https://www.lobaro.com/lobaro-iot-produkte-dienste/
  - Lobaro Tools:
      - Lobaro Maintenance Tool: tools/lobaro-tool.md
      - USB Config Adapter: tools/usb-config-adapter.md
  - Lobaro IoT Platform:
    - Manual: platform/index.md
    - Integrations: platform/integrations.md
    - Parser: platform/parser.md
    - Table Config: platform/table-config.md
  - Lobaro Shop: https://www.lobaro-shop.com/
  - Contact / Impressum: https://www.lobaro.com/contact/

