site_name: Lobaro Documentation
site_description: Online documentation of the Lobaro GmbH, Industrial IoT Solutions. Manuals for our IoT Devices.
theme:
    name: cinder
#    name: readthedocs
    highlightjs: true
repo_url: "https://github.com/lobaro/docs"
markdown_extensions:
    - def_list
    - toc:
    - admonition
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
    - "css/lobarodoc.css"
extra_javascript:
    - "js/mermaid.min.js"
nav:
    - Documentation Home: index.md
    - Company Home: https://www.lobaro.com/lobaro-iot-produkte-dienste/
    - Contact / Impressum: https://www.lobaro.com/contact/
